# Site settings
title: Miquel Mariano
description: 'Apasionado de la montaña y de todo lo relacionado con mover los pies | Consultor TI en Ncora | VCP5/6-DCV | vExpert2016'
url: 'https://miquelMariano.github.com' 
baseurl: '/'
#google_analytics: 'UA-501066-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Josh Gerdes'
  email: josh@joshgerdes.com
  twitter_username: joshgerdes
  # facebook_username: joshgerdes
  github_username:  joshgerdes
  linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#gems: ['jekyll-paginate']
#exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'src']