title: Stack Problems
description: My Personal Stack Problems
author: Miquel Mariano
github: https://github.com/miquelMariano
about: Consultor TI en Ncora | VCP5/6-DCV | vExpert 2016/17 | Apasionado de la montaña | Bike | Trail | Run | Padre de Aina
disqus_shortname: miquelmariano
google_analytics: UA-89683320-1
avatar_url: /static/img/profile.jpg
imagesposts2016: /static/img/_posts/2016
imagesposts2017: /static/img/_posts/2017

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
#    - icon: fa-facebook
#      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/miquelMariano"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/miquelMariano"
#    - icon: fa-stack-exchange
#      link: "#"
    - icon: fa-github
      link: "https://github.com/miquelMariano"

share:
  twitter_username: miquelMariano
#  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://miquelMariano.github.io"
baseurl: ""
paginate: 10
per_page: 10
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
